Update sns_uat.yml

diff --git a/.github/workflows/sns_uat.yml b/.github/workflows/sns_uat.yml
--- a/.github/workflows/sns_uat.yml
+++ b/.github/workflows/sns_uat.yml
@@ -2,15 +2,27 @@ name: Deploy SNS UAT
 
 on:
   workflow_dispatch:
+    inputs:
+      branch:
+        description: 'Branch or Tag to Deploy'
+        required: true
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-    
     - name: Checkout code
       uses: actions/checkout@v2
+      with:
+        ref: ${{ github.event.inputs.branch }}
+
+    - name: Verify branch
+      run: |
+        if [ "${{ github.ref }}" != "refs/heads/${{ github.event.inputs.branch }}" ]; then
+          echo "Error: The current branch does not match the input branch."
+          exit 1
+        fi
 
     - name: npm install
       run: npm install
